version: 1.0.{build}

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

install:
  - set PATH=%PATH%;C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;
  - 'git clone https://github.com/dlfcn-win32/dlfcn-win32.git'
  - 'pushd dlfcn-win32'
  - './configure'
  - 'env CC=gcc make'
  - 'make install'
  - 'ln -s /mingw/lib/libdl.a /mingw64/lib/libdl.a'
  - 'popd'
  
build_script:
  - 'pushd %APPVEYOR_BUILD_FOLDER%'
  - 'make binary'

artifacts:
  - path: '*.exe'
