version: 1.0.{build}

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

install:
  - set PATH=%PATH%;C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;
  - bash -lc "printenv PATH"
  - bash -lc "git clone https://github.com/dlfcn-win32/dlfcn-win32.git"
  - bash -lc "pushd dlfcn-win32"
  - bash -lc "./configure"
  - bash -lc "'env CC=gcc make"
  - bash -lc "make install"
  - bash -lc "ln -s /mingw/lib/libdl.a /mingw64/lib/libdl.a"
  - bash -lc "popd"
  
build_script:
  - bash -lc "pushd %APPVEYOR_BUILD_FOLDER%"
  - bash -lc "make binary"

artifacts:
  - path: '*.exe'
